import type { Course } from '@/interfaces/course'

export const data: Array<Course> = [
  {
    id: 1,
    cover: '/images/courses/c2.jpg',
    title: 'Coming together makes us stronger',
    rating: 5,
    ratingCount: 8,
    price: 25,
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/courses/c3.jpeg',
    title: 'A chance to Succeed',
    rating: 5,
    ratingCount: 15,
    price: 20,
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/courses/c4.jpg',
    title: 'Women Empowerment in ICT',
    rating: 4,
    ratingCount: 7,
    price: 30,
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/courses/c5.jpg',
    title: 'A voice to the young generation',
    rating: 4,
    ratingCount: 12,
    price: 30,
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/courses/c6.jpg',
    title: 'Skills training to give hope',
    rating: 4,
    ratingCount: 32,
    price: 35,
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/courses/c7.jpg',
    title: 'Income generating activities',
    rating: 5,
    ratingCount: 14,
    price: 35,
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/courses/c8.jpg',
    title: "Working for women's economic justice",
    rating: 4,
    ratingCount: 6,
    price: 25,
    category: 'Economic',
  },
]
